env:
  REF_NAME: ${{ inputs.ref_name||github.ref_name }}

name: Cache
run-name: Caching ${{inputs.ref_name||github.ref_name}}

on:
  workflow_call:
    inputs:
      ref_name:
        description: 'Tag'
        required: false
        type: string
    outputs:
      cache-key:
        description: 'Cache Key'
        value: ${{jobs.cache.outputs.cache-key}}
jobs:
  cache:
    name: Cache ${{inputs.ref_name||github.ref_name}}
    outputs:
      cache-key: ${{steps.setup.outputs.cache-key}}
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{env.REF_NAME}}

      - name: Setup Env
        shell: bash
        id: setup
        run: |
          echo "installationPath=$(vswhere -all -legacy -property installationPath)">>$GITHUB_OUTPUT
          KEY=$(git ls-tree -r ${{env.REF_NAME}}|grep ^160000|sort -d|md5sum|cut -d' ' -f1)
          echo "cache-hash=$KEY" >>$GITHUB_OUTPUT
          echo "cache-key=${{ runner.os }}-$KEY-submodules" >>$GITHUB_OUTPUT

      - name: Restore cached submodules
        id: cache-submodules-restore
        uses: actions/cache@v4
        with:
          path: .git/modules
          key: ${{steps.setup.outputs.cache-key}}

      - name: Pull submodules
        shell: bash
        run: |
          git submodule update --init --recursive --depth 1
